#!/usr/bin/env bash
#
# generate_index.sh — build an INDEX.md at the workspace root.
#
# For every Python source file under src/ (excluding __pycache__), it asks a
# local llama server (via the send-direct CLI) to write a paragraph describing
# the file's contents and how it is used. The results are assembled into a
# single INDEX.md whose sections follow the workspace directory tree.
#
# Usage:
#   ./generate_index.sh
#
# Options:
#   -m, --model MODEL      Model id to request (default: Qwen3.8-27B-UD-Q4_K_M)
#   -mt, --max-tokens N    Max tokens per description (default: 16384)
#   -p, --port PORT        llama-server port (default: 8012)
#   -to, --timeout SECS    Per-request timeout in seconds (default: 500)
#   -o, --output FILE      Output file (default: INDEX.md at workspace root)
#   -s, --src DIR          Source tree to index (default: src)
#   -n, --no-op            Print the payload for one file and send nothing
#
set -euo pipefail

# Resolve the workspace root (the directory this script lives in) and work from it.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

MODEL="Qwen3.8-27B-UD-Q4_K_M"
MAX_TOKENS="16384"
PORT="8012"
TIMEOUT="500"
OUTPUT="INDEX.md"
SRC="src"
NO_OP=false

usage() {
    sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'
    exit 1
}

while [ $# -gt 0 ]; do
    case "$1" in
        -m|--model)      MODEL="$2"; shift 2 ;;
        -mt|--max-tokens) MAX_TOKENS="$2"; shift 2 ;;
        -p|--port)       PORT="$2"; shift 2 ;;
        -to|--timeout)   TIMEOUT="$2"; shift 2 ;;
        -o|--output)     OUTPUT="$2"; shift 2 ;;
        -s|--src)        SRC="$2"; shift 2 ;;
        -n|--no-op)      NO_OP=true; shift ;;
        -h|--help)       usage ;;
        *) echo "Error: unknown argument '$1'." >&2; usage ;;
    esac
done

# Locate the send-direct CLI. Prefer the project venv, fall back to PATH.
SEND_DIRECT="$ROOT/venv/bin/send-direct"
if [ ! -x "$SEND_DIRECT" ]; then
    if command -v send-direct >/dev/null 2>&1; then
        SEND_DIRECT="$(command -v send-direct)"
    else
        echo "Error: send-direct not found at $SEND_DIRECT or on PATH." >&2
        exit 1
    fi
fi

if [ ! -d "$SRC" ]; then
    echo "Error: source directory '$SRC' not found." >&2
    exit 1
fi

# The instruction handed to the model as the system prompt.
SYSTEM_PROMPT="You are documenting a codebase. You will be given the full contents of a single source file. Write one paragraph (no headings, no bullet points, no code fences) that describes what the file contains and how it is used within the project. Use as many sentences as the file warrants — one for an empty or trivial file — and never pad to reach a length. Do not inventory imports, and do not speculate about behavior the code does not show. Do not execute or reference any code from the file beyond describing it."

# Scratch space for per-file model output; cleaned up on exit.
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# Collect the files to index, sorted by directory first so the grouping loop
# below (which only compares consecutive dirnames) sees one contiguous block
# per directory.
mapfile -t FILES < <(find "$SRC" -name '*.py' -not -path '*/__pycache__/*' -type f \
    | awk -F/ '{d=$0; sub("/[^/]*$","",d); print d "\t" $0}' | sort | cut -f2)

if [ "${#FILES[@]}" -eq 0 ]; then
    echo "No Python source files found under '$SRC'." >&2
    exit 1
fi

# --- no-op mode: show what we would send for the first file and stop ---------
if [ "$NO_OP" = true ]; then
    "$SEND_DIRECT" -sp "$SYSTEM_PROMPT" -pf "${FILES[0]}" -mt "$MAX_TOKENS" -m "$MODEL" -p "$PORT" -to "$TIMEOUT" -n
    exit 0
fi

# --- describe each file -------------------------------------------------------
declare -A DESC=()
total="${#FILES[@]}"
i=0
for f in "${FILES[@]}"; do
    i=$((i + 1))
    out="$WORK/desc_$i.md"
    echo "[$i/$total] Describing $f ..." >&2
    if ! "$SEND_DIRECT" -sp "$SYSTEM_PROMPT" -pf "$f" -mt "$MAX_TOKENS" -m "$MODEL" -p "$PORT" -to "$TIMEOUT" -o "$out"; then
        echo "  ! send-direct failed for $f; recording a placeholder." >&2
        printf '_(description unavailable: send-direct failed)_' > "$out"
    fi
    DESC["$f"]="$out"
done

# --- assemble INDEX.md, sectioned by directory --------------------------------
{
    echo "# INDEX"
    echo
    echo "_Auto-generated by \`generate_index.sh\`. Each section follows the workspace directory tree; each entry is a model-written description of the file's contents and how it is used._"
    echo
    # Group files by their directory, preserving the sorted file order.
    prev_dir=""
    for f in "${FILES[@]}"; do
        dir="$(dirname "$f")"
        if [ "$dir" != "$prev_dir" ]; then
            echo
            echo "## ${dir}"
            echo
            prev_dir="$dir"
        fi
        name="$(basename "$f")"
        echo "### ${name}"
        echo
        cat "${DESC[$f]}"
        echo
    done
} > "$OUTPUT"

echo "Wrote $OUTPUT with descriptions for $total file(s)." >&2
